Repository zilliztech/milvus-cdc, pull requests merged in 2025-02, with the labels that each got.

#181 ci: update artifact name to include metastore in CI workflow
  .github/workflows/ci.yaml
  core/reader/collection_reader.go
  core/reader/replicate_channel_manager.go
  server/cdc_impl.go
  server/configs/data_diff.yaml
  server/tool/data_diff/main.go
  server/tool/msg_stream.go
  server/tool/position_decode.go
  server/tool/yaml_config.go
  tests/deployment/channel_4/docker-compose.yml
  tests/deployment/downstream/standalone-values-8.yaml
  tests/deployment/downstream/standalone-values-auth.yaml
  tests/deployment/downstream/standalone-values.yaml
  tests/deployment/upstream/docker-compose.yml
Labels: approved, size/L, lgtm

#182 test: fix fail fast
  .github/workflows/ci.yaml
Labels: approved, size/XS, lgtm

#184 ci: add nightly
  .github/workflows/nightly.yaml
  scripts/get_latest_tag.py
Labels: approved, size/L, lgtm

#185 feat: update ShouldReadFunc to return additional boolean for collection replication and modify related logic
  core/reader/collection_reader.go
  core/reader/collection_reader_test.go
  server/cdc_impl.go
  server/cdc_impl_test.go
  server/model/common.go
Labels: approved, size/L

#186 feat: implement logging for insert and delete messages, add maintenance commands for log management
  server/cdc_impl.go
  server/configs/data_diff.yaml
  server/maintenance/log_msg.go
  server/maintenance/maintenance.go
  server/server.go
  server/tool/data_diff/main.go
  server/tool/position_decode.go
  server/tool/yaml_config.go
Labels: approved, size/L, lgtm
