Repository zilliztech/milvus-cdc, pull requests merged in 2025-05, with the labels that each got.

#214 feat: add batch mode support in Milvus package initialization and related configurations
  core/go.mod
  core/go.sum
  core/reader/replicate_channel_manager.go
  core/reader/replicate_channel_manager_test.go
  core/util/milvus_param.go
  server/cdc_impl_test.go
  server/config.go
  server/configs/cdc.yaml
  server/go.mod
  server/go.sum
  server/main/main.go
Labels: approved, lgtm, size/M

#217 enhance: Upgrade Milvus
  tests/deployment/channel_4/docker-compose.yml
  tests/deployment/downstream/standalone-values-8.yaml
  tests/deployment/downstream/standalone-values-auth.yaml
  tests/deployment/downstream/standalone-values.yaml
  tests/deployment/upstream/docker-compose.yml
  tests/testcases/test_cdc_sync_requests.py
Labels: approved, lgtm, size/M

#216 test: Add cdc testcases for json path index
  .github/workflows/ci.yaml
  tests/base/checker.py
  tests/requirements.txt
  tests/testcases/test_cdc_create.py
  tests/testcases/test_cdc_database.py
  tests/testcases/test_cdc_sync_requests.py
Labels: approved, lgtm, size/M, do-not-merge/hold

#220 feat: add privilege group management functions
  .github/workflows/ci.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/image_publish.yml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  Dockerfile
  core/api/data_handler.go
  core/api/param.go
  core/go.mod
  core/go.sum
  core/mocks/data_handler.go
  core/util/msgpack.go
  core/writer/channel_writer.go
  core/writer/milvus_handler.go
  server/cdc_impl.go
  server/configs/cdc.yaml
  server/go.mod
  server/go.sum
Labels: approved, size/L, lgtm

#223 refactor: clean up import statements for consistency across test files
  core/api/meta_op_test.go
  core/api/replicate_manager_test.go
  core/reader/etcd_op_test.go
  core/reader/replicate_channel_manager_test.go
  core/writer/channel_writer_test.go
  server/cdc_impl_test.go
  server/tool/collection_position.go
  server/tool/msg_count/main.go
Labels: approved, size/S, lgtm

#215 enable rbac for cdc test
  .github/workflows/ci.yaml
  deployment/docker/cdc.yaml
  scripts/check_healthy.sh
  tests/README.md
  tests/conftest.py
  tests/deployment/cdc_task_op.py
  tests/deployment/channel_4/docker-compose.yml
  tests/deployment/downstream/standalone-values-8.yaml
  tests/deployment/downstream/standalone-values-auth.yaml
  tests/deployment/downstream/standalone-values.yaml
  tests/deployment/milvus/docker-compose.yml
  tests/deployment/milvus/downstream.yaml
  tests/deployment/milvus/upstream.yaml
  tests/deployment/upstream/docker-compose.yml
  tests/requirements.txt
  tests/testcases/test_cdc_create.py
  tests/testcases/test_cdc_database.py
  tests/testcases/test_cdc_delete.py
  tests/testcases/test_cdc_e2e.py
  tests/testcases/test_cdc_get.py
  tests/testcases/test_cdc_list.py
  tests/testcases/test_cdc_pause.py
  tests/testcases/test_cdc_resume.py
  tests/testcases/test_cdc_sync_requests.py
Labels: approved, lgtm, size/XXL

#218 enhance: Add nullable and default test cases
  tests/testcases/test_cdc_sync_requests.py
Labels: approved, lgtm, size/M
