Repository zilliztech/milvus-cdc, pull requests merged in 2025-04, with the labels that each got.

#204 refactor: replace base64 encoding with utility functions for seek position handling
  core/reader/channel_reader.go
  core/reader/channel_reader_test.go
  server/cdc_impl.go
  tests/testcases/test_cdc_resume.py
Labels: approved, lgtm, size/M

#205 feat: set default values for PackerConfig fields in NewPacker function
  server/msgpacker/packer.go
  tests/testcases/test_cdc_resume.py
Labels: approved, size/S, lgtm

#207 fix: update upload-artifact action to v4 in release workflow
  .github/workflows/release.yaml
Labels: approved, size/S, lgtm

#212 feat: add DeleteTaskCollectionPosition method to handle collection position deletion
  .github/workflows/ci.yaml
  .github/workflows/nightly.yaml
  server/cdc_impl.go
  server/model/meta/task.go
  server/model/request/get.go
  server/store/meta_op.go
  server/writer_callback.go
Labels: approved, size/L, lgtm

#213 test: fix Python dependency security issues
  .github/workflows/ci.yaml
  .github/workflows/nightly.yaml
  tests/requirements.txt
Labels: approved, size/S, lgtm
